# Generated by Django 4.2 on 2026-04-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('camera_id', models.PositiveIntegerField()),
                ('pen_index', models.PositiveIntegerField()),
                ('roi_xyxy_norm_in_camroi', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['camera_id', 'pen_index'],
            },
        ),
        migrations.CreateModel(
            name='PenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_relative_path', models.CharField(blank=True, max_length=255)),
                ('snapshot_updated_at', models.DateTimeField(blank=True, null=True)),
                ('detections_json', models.JSONField(blank=True, default=list)),
                ('today_distance_m', models.FloatField(default=0.0)),
                ('yesterday_distance_m', models.FloatField(default=0.0)),
                ('last_7_days_distance_m', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='antra.pen')),
            ],
            options={
                'verbose_name': 'Pen state',
                'verbose_name_plural': 'Pen states',
            },
        ),
    ]
