# Generated by Django 4.2 on 2026-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antra', '0002_pen_penstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='image_height_m',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='penstate',
            name='daily_distance_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='penstate',
            name='tracking_state_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
