# Generated by Django 4.2 on 2026-04-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antra', '0003_pen_image_height_m_penstate_daily_distance_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenActivityQuarterHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('distance_total_m', models.FloatField(default=0.0)),
                ('distance_mean_per_track_m', models.FloatField(default=0.0)),
                ('distance_variance_per_track_m', models.FloatField(default=0.0)),
                ('present', models.BooleanField(default=False)),
                ('presence_seconds', models.FloatField(default=0.0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('detection_count', models.PositiveIntegerField(default=0)),
                ('track_distance_json', models.JSONField(blank=True, default=dict)),
                ('seen_track_ids_json', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_hour_activities', to='antra.pen')),
            ],
            options={
                'ordering': ['-window_start', 'pen_id', 'label'],
                'unique_together': {('pen', 'label', 'window_start')},
            },
        ),
    ]
