FROM python:3.9.16-slim
LABEL authors="mjirik"

COPY ./src/animaltracking/requirements.txt /animaltracking/requirements.txt

# install system dependencies
RUN apt-get update --yes &&  \
    apt-get install --yes \
    wget \
    uvicorn \
    unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# install python dependencies
ENV APP_DIR='/animaltracking'
WORKDIR $APP_DIR
RUN pip install --no-cache-dir --upgrade pip build && \
    pip install --no-cache-dir --compile -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/* /var/tmp/*

COPY ./src/animaltracking/start_dev.sh /animaltracking/start_dev.sh

# expose ports and run application
WORKDIR $APP_DIR
ENV PYTHONUNBUFFERED=1
EXPOSE 8080
CMD bash ./start_dev.sh